---
name: Build and Deploy

on: push  # yamllint disable-line rule:truthy

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: crate-ci/typos@v1.29.5

      - uses: ibiqlik/action-yamllint@v3

      - uses: actions/setup-node@v4
        with:
          node-version: current
      - name: setup-stylelint
        run: npm install stylelint stylelint-config-standard @stylistic/stylelint-plugin postcss -g

      - uses: extractions/setup-just@v2

      - name: run-lints
        run: just lint-ci

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0'

      - name: Install html2pdf
        run: |
          wget https://github.com/ilaborie/html2pdf/releases/download/v0.8.1/html2pdf-x86_64-unknown-linux-gnu.tar.xz
          tar xf html2pdf-x86_64-unknown-linux-gnu.tar.xz
          sudo mv html2pdf-x86_64-unknown-linux-gnu/html2pdf /usr/bin

      - name: Build content
        run: just build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
